on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  
      - name: Install Dependencies
        run: pip install twine
      - name: Build and Push
      # cd src
        run: |
          python setup.py sdist
          twine upload dist/* --username __token__
        env:
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

  test:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'submit ') 
    steps:
      - uses: ./
        env:
          UBIT_USERNAME: ${{ secrets.UBITUsername }}
          UBIT_PASSWORD: ${{ secrets.UBITPassword }}
          COMMIT: ${{ github.event.head_commit.message }}
# ra