on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: A job to say hello
    if: startsWith(github.event.head_commit.message, 'submit ') 
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        env:
          UBIT_USERNAME: ${{ secrets.UBITUsername }}
          UBIT_PASSWORD: ${{ secrets.UBITPassword }}
